<?php
/**
 * Indexa - NF-e. 
 * 
 * @category    design
 * @package     default_default
 * @author     Indexa Development Team <desenvolvimento@indexainternet.com.br>
 * @copyright   Copyright (c) 2011 Indexa - http://www.indexainternet.com.br  
 */
$nfCollection = $this->getNf();
?>
<?php if ($nfCollection && count($nfCollection) > 0): ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo Mage::helper('sales')->__('NF-e') ?></h4>
        </div>
        <div class="grid np ">
            <div style="border: 1px solid #CCCCCC">
                        <?php foreach ($nfCollection as $nf): ?>        
    

                            <?php $nfShip = $this->getNfCollection($nf->getId()); ?>
                            <?php if (count($nfShip) > 0): ?>    

                                <?php foreach ($nfShip as $ship): ?> <br/>
                                    <strong>&nbsp; Envio <?php echo $ship->getId() ?></strong>
                                    <div class="divider"></div>

                                    <table cellspacing="0" class="data order-tables">
                                        <thead>

                                            <tr class="headings">
                                                <th width="5%">Request Id</th>
                                                <th width="45%">Message</th>
                                                <th width="13%">Date</th>
                                                <th width="5%">Status</th>
                                                <th width="27%"><span class="nobr">Actions</span></th>
                                            </tr>
                                        </thead>
                                        <?php $nfRequest = $this->getRequestCollection($ship->getId()); ?>
                                        <?php if (count($nfRequest) > 0): ?>    
                                            <?php foreach ($nfRequest as $request): ?>  

                                                <tbody class="even">

                                                    <tr class="border">
                                                        <td>
                                                            <?php echo $request->getId() ?>
                                                        </td>
                                                        <td class="a-left">
                                                            <?php if (Indexa_Nfe_Helper_Data::NFE_SHIPMENT_STATUS_FINISHED == $request->getStatus()): ?> 
                                                                Chave de Acesso: <?php echo $request->getMessages(); ?>
                                                            <?php elseif (Indexa_Nfe_Helper_Data::NFE_SHIPMENT_STATUS_ERROR == $request->getStatus()): ?>
                                                                Error Message: <?php echo $request->getMessages() ?>
                                                            <?php elseif (Indexa_Nfe_Helper_Data::NFE_SHIPMENT_STATUS_PROCESSING == $request->getStatus()): ?>
                                                                Request Number: <?php echo $request->getMessages() ?>
                                                            <?php endif; ?>
                                                        </td>
                                                        <td class="a-left">
                                                            <?php echo $this->helper('core')->formatDate($request->getExecutedAt(), 'large') ?>
                                                        </td>
                                                        <td class="a-center">
                                                            <?php echo $this->helper('nfe')->__($request->getStatus()) ?>
                                                        </td>
                                                        <td class="a-center">
                                                            <?php if (Indexa_Nfe_Helper_Data::NFE_SHIPMENT_STATUS_FINISHED == $request->getStatus() ): ?>
                                                                <?php if( file_exists(Mage::getBaseDir() . '/nf/xml/'.$request->getMessages().'.xml') ): ?>
                                                                    <button style="" class="scalable save" type="button" onclick="setLocation( '<?php echo $this->escapeHtml($this->getUrl('nfe/adminhtml_nfe/xml', array('id' => $request->getMessages()) )) ?>')" ><span>Download XML</span></button>&nbsp;
                                                                <?php endif; ?>    
                                                                <?php if( file_exists(Mage::getBaseDir() . '/nf/pdf/'.$request->getMessages().'.pdf') ): ?>
                                                                    <button style="" class="scalable save" type="button" onclick="setLocation( '<?php echo $this->escapeHtml($this->getUrl('nfe/adminhtml_nfe/pdf', array('id' => $request->getMessages()) )) ?>')" ><span>Download PDF</span></button>
                                                                <?php endif; ?>    
                                                            <?php elseif (Indexa_Nfe_Helper_Data::NFE_SHIPMENT_STATUS_ERROR == $request->getStatus() && $this->getLastErrorId($ship->getId()) == $request->getId() && !$this->getLastFinishedId($ship->getId()) ): ?>
                                                                <button style="" class="scalable save" type="button" onclick="setLocation( '<?php echo $this->escapeHtml($this->getUrl('nfe/adminhtml_nfe/edit', array('id' => $request->getId()) )) ?>')" ><span>Editar Envio</span></button>
                                                            <?php endif; ?>    
                                                        </td>
                                                    </tr>
                                                </tbody>

                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </table>
                                <?php endforeach; ?>
                            <?php endif; ?>
                           
                        <?php endforeach; ?>
                   </div>
        </div>
    </div>
    <div class="clear"></div>
    <br />
<?php endif; ?>